{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 63,
   "metadata": {
    "scrolled": false
   },
   "outputs": [],
   "source": [
    "import csv\n",
    "from PIL import Image, ImageDraw\n",
    "\n",
    "#Set up global list and drawing elements\n",
    "boxes = []\n",
    "im = Image.new('RGB', (1600, 2800), (255, 255, 255))\n",
    "draw = ImageDraw.Draw(im)\n",
    "\n",
    "#Method to draw the rectangles on to an image file in the same folder\n",
    "def drawRect(x, y, width, height):\n",
    "    draw.rectangle((x,y,width,height), fill=(255, 0 , 0), outline=(0, 0, 0))\n",
    "    im.save('./image.jpg', quality=95)\n",
    "\n",
    "#Hard-coded csv file read in to a list\n",
    "#** Note to Caleb: IDK how to make this a dialog box thing, maybe yours is better\n",
    "with open('toy_problem.csv', newline = '') as csvfile:\n",
    "    reader = csv.reader(csvfile, delimiter=',')\n",
    "    for row in reader:\n",
    "        boxes.append(row)\n",
    "\n",
    "#Rectangle object class initiating all the properties\n",
    "class Rectangle:\n",
    "    def __init__(self, index, width, height):\n",
    "        self.index = index\n",
    "        self.xpos = 0\n",
    "        self.ypos = 0\n",
    "        self.width = width\n",
    "        self.height = height\n",
    "        self.drawn = False\n",
    "\n",
    "#Solution object class is a representation of a solution, which is stored as a list of rectangles\n",
    "class Solution:\n",
    "    def __init__(self, boxes = boxes):\n",
    "        self.boxlist = []\n",
    "        self.drawnlist = []\n",
    "        for i in range(0, len(boxes)):\n",
    "            rect = Rectangle(i, boxes[i][0], boxes[i][1])\n",
    "            self.boxlist.append(rect)\n",
    "     \n",
    "    #Method to get the height at which a Rectangle can be drawn without overlap at a given point\n",
    "    def getMaxHeight(self, x, width):\n",
    "        maxHeight = 0\n",
    "        for box in self.boxlist:\n",
    "            if box.xpos < x + width and box.ypos + (40 * int(box.height)) >= maxHeight \n",
    "            and box.drawn and x < box.xpos + (40 * int(box.width)):\n",
    "                maxHeight = box.ypos + (40 * int(box.height))\n",
    "        return maxHeight\n",
    "    \n",
    "    #Method to stack/place the Rectangles onto a sheet\n",
    "    def stackBoxes(self, x, y, width, height):\n",
    "        if x + width > im.width:\n",
    "            x = 0\n",
    "        y = self.getMaxHeight(x, width)\n",
    "        drawRect(x, y, x + width, y + height)\n",
    "        x += width\n",
    "        return x, y\n",
    "\n",
    "#Initial solution generator, the Rectangles read in earlier are placed onto the sheet in the order \n",
    "#they appear on the CSV\n",
    "def initialSolution():\n",
    "    temp_boxes = Solution(boxes)\n",
    "    init_x = 0\n",
    "    init_y = 0\n",
    "    #**Note to Caleb: Iterator cause I was testing, but would be later swapped in for a foreach loop\n",
    "    for i in range(100):\n",
    "        box = temp_boxes.boxlist[i]\n",
    "        box.xpos = init_x\n",
    "        box.ypos = init_y\n",
    "        init_x, init_y = temp_boxes.stackBoxes(init_x, init_y, 40 * int(box.width), 40 * int(box.height))\n",
    "        box.ypos = init_y\n",
    "        box.xpos = init_x - 40 * int(box.width)\n",
    "        #print(str(box.xpos) + ' ' + str(box.ypos) + ' ' + str(40 * int(box.width)) + ' ' + str(40 * int(box.height)))\n",
    "        box.drawn = True\n",
    "        \n",
    "initialSolution()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.7.6"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
